const data = {
  products: [
    {
      _id: "1",
      name: "Black & Grey Checkered Shirt",
      category: "Shirts",
      image: "./images/checkeredShirt.jpg",
      price: 120,
      brand: "Checkered",
      rating: 4.5,
      numReviews: 10,
      description: "high quality products",
    },
    {
      _id: "2",
      name: "Black & Grey Checkered Shirt",
      category: "Shirts",
      image: "./images/checkeredShirt.jpg",
      price: 120,
      brand: "Checkered",
      rating: 4.5,
      numReviews: 10,
      description: "high quality products",
    },
    {
      _id: "3",
      name: "Black & Grey Checkered Shirt",
      category: "Shirts",
      image: "./images/checkeredShirt.jpg",
      price: 120,
      brand: "Checkered",
      rating: 4.5,
      numReviews: 10,
      description: "high quality products",
    },
    {
      _id: "4",
      name: "Orange Jacket",
      category: "Jacket",
      image: "./images/OrangeJacket.jpg",
      price: 150,
      brand: "Nike",
      rating: 4.0,
      numReviews: 10,
      description: "high quality products",
    },
    {
      _id: "5",
      name: "Dark Blue Denim Jacket",
      category: "Jacket",
      image: "./images/DenimJacket.jpg",
      price: 180,
      brand: "Denim",
      rating: 4.5,
      numReviews: 10,
      description: "high quality products",
    },
  ],
};
export default data;
